### ISSUE TITLE
Change Name?

### ISSUE THREAD

**Issue by araddon** [owainlewis/unify#1]
I definitely recommend changing name, I use ubuntu linux and ran `go get` on this project to try this it out, and definitely got un desirable effects https://unity.ubuntu.com/

**Comment by owainlewis** [comment]
Thanks. I'll have to think of a new name : ) :+1:

**Comment by araddon** [comment]
unify?

**Comment by owainlewis** [comment]
Ah yes that's a good one. I'll make the change the repo and executable name tomorrow. Thanks for the input. :+1:

**Comment by owainlewis** [comment]
Done.
